version: '3'

services:
  <challenge-name>:
    image: localhost:56156/how-do-I-meet-friend
    build:
      context: ../../../ # do not change
      dockerfile: Challenges/Web/my-ctf/Dockerfile
    networks:
      nw0:
    deploy:
      resources:
        limits:
          memory: 200m
          cpus: '0.1'

networks:
  nw0:
    external: true